# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Anaconda\Library\bin\NewsNew.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StackedWidget(object):
    def setupUi(self, StackedWidget):
        StackedWidget.setObjectName("StackedWidget")
        StackedWidget.resize(950, 1000)
        StackedWidget.setMinimumSize(QtCore.QSize(950, 1000))
        StackedWidget.setMaximumSize(QtCore.QSize(950, 1000))
        self.News = QtWidgets.QWidget()
        self.News.setObjectName("News")
        self.N_scrollArea = QtWidgets.QScrollArea(self.News)
        self.N_scrollArea.setGeometry(QtCore.QRect(0, 0, 951, 1000))
        self.N_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.N_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.N_scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.N_scrollArea.setWidgetResizable(False)
        self.N_scrollArea.setObjectName("N_scrollArea")
        self.N_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.N_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 928, 4098))
        self.N_scrollAreaWidgetContents.setObjectName("N_scrollAreaWidgetContents")
        self.N_HSV_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_HSV_Pic.setGeometry(QtCore.QRect(20, 2880, 901, 361))
        self.N_HSV_Pic.setText("")
        self.N_HSV_Pic.setPixmap(QtGui.QPixmap("ronaldo.bmp"))
        self.N_HSV_Pic.setScaledContents(True)
        self.N_HSV_Pic.setObjectName("N_HSV_Pic")
        self.N_Acc_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Acc_Head.setGeometry(QtCore.QRect(20, 1110, 901, 51))
        self.N_Acc_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_Acc_Head.setObjectName("N_Acc_Head")
        self.N_JD_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_JD_Teaser.setGeometry(QtCore.QRect(20, 1700, 901, 41))
        self.N_JD_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_JD_Teaser.setObjectName("N_JD_Teaser")
        self.N_JD_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_JD_Pic.setGeometry(QtCore.QRect(20, 1260, 911, 381))
        self.N_JD_Pic.setText("")
        self.N_JD_Pic.setPixmap(QtGui.QPixmap("johnny-depp.bmp"))
        self.N_JD_Pic.setObjectName("N_JD_Pic")
        self.N_Trump_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Trump_Pic.setGeometry(QtCore.QRect(20, 3410, 901, 361))
        self.N_Trump_Pic.setText("")
        self.N_Trump_Pic.setPixmap(QtGui.QPixmap("trumptwitter.bmp"))
        self.N_Trump_Pic.setScaledContents(True)
        self.N_Trump_Pic.setObjectName("N_Trump_Pic")
        self.N_Munich_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Munich_Head.setGeometry(QtCore.QRect(20, 2170, 901, 51))
        self.N_Munich_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_Munich_Head.setObjectName("N_Munich_Head")
        self.N_Trump_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Trump_Head.setGeometry(QtCore.QRect(20, 3790, 901, 51))
        self.N_Trump_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_Trump_Head.setObjectName("N_Trump_Head")
        self.N_Trump_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Trump_Teaser.setGeometry(QtCore.QRect(20, 3830, 901, 81))
        self.N_Trump_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_Trump_Teaser.setObjectName("N_Trump_Teaser")
        self.N_HSV_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_HSV_Button.setGeometry(QtCore.QRect(790, 3320, 93, 28))
        self.N_HSV_Button.setObjectName("N_HSV_Button")
        self.N_HSV_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(2))
        self.N_GoT_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_GoT_Head.setGeometry(QtCore.QRect(20, 2700, 901, 51))
        self.N_GoT_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_GoT_Head.setObjectName("N_GoT_Head")
        self.N_Munich_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_Munich_Button.setGeometry(QtCore.QRect(810, 2270, 93, 28))
        self.N_Munich_Button.setObjectName("N_Munich_Button")
        self.N_Munich_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(6))
        self.N_Merkel_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_Merkel_Button.setGeometry(QtCore.QRect(820, 670, 93, 28))
        self.N_Merkel_Button.setObjectName("N_Merkel_Button")
        self.N_Merkel_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(7))
        self.N_Trump_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_Trump_Button.setGeometry(QtCore.QRect(790, 3880, 93, 28))
        self.N_Trump_Button.setObjectName("N_Trump_Button")
        self.N_Trump_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(4))
        self.N_Bottom = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Bottom.setGeometry(QtCore.QRect(10, 4050, 871, 31))
        self.N_Bottom.setObjectName("N_Bottom")
        self.N_Acc_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Acc_Pic.setGeometry(QtCore.QRect(20, 730, 901, 371))
        self.N_Acc_Pic.setText("")
        self.N_Acc_Pic.setPixmap(QtGui.QPixmap("autounfall.bmp"))
        self.N_Acc_Pic.setScaledContents(True)
        self.N_Acc_Pic.setObjectName("N_Acc_Pic")
        self.N_Acc_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_Acc_Button.setGeometry(QtCore.QRect(810, 1180, 93, 28))
        self.N_Acc_Button.setObjectName("N_Acc_Button")
        self.N_Acc_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(3))
        self.N_GoT_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_GoT_Teaser.setGeometry(QtCore.QRect(20, 2760, 901, 81))
        self.N_GoT_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_GoT_Teaser.setObjectName("N_GoT_Teaser")
        self.N_Merkel_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Merkel_Pic.setGeometry(QtCore.QRect(20, 210, 911, 381))
        self.N_Merkel_Pic.setText("")
        self.N_Merkel_Pic.setPixmap(QtGui.QPixmap("angela-merkel-barack-obama-berlin.bmp"))
        self.N_Merkel_Pic.setObjectName("N_Merkel_Pic")
        self.N_Merkel_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Merkel_Teaser.setGeometry(QtCore.QRect(20, 640, 911, 51))
        self.N_Merkel_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_Merkel_Teaser.setObjectName("N_Merkel_Teaser")
        self.N_Top_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Top_Head.setGeometry(QtCore.QRect(350, 10, 240, 152))
        self.N_Top_Head.setAutoFillBackground(False)
        self.N_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.N_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.N_Top_Head.setWordWrap(False)
        self.N_Top_Head.setObjectName("N_Top_Head")
        self.N_GoT_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_GoT_Button.setGeometry(QtCore.QRect(800, 2830, 93, 28))
        self.N_GoT_Button.setObjectName("N_GoT_Button")
        self.N_GoT_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(1))
        self.N_JD_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_JD_Head.setGeometry(QtCore.QRect(20, 1650, 901, 51))
        self.N_JD_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_JD_Head.setObjectName("N_JD_Head")
        self.N_JD_Button = QtWidgets.QPushButton(self.N_scrollAreaWidgetContents)
        self.N_JD_Button.setGeometry(QtCore.QRect(810, 1740, 93, 28))
        self.N_JD_Button.setObjectName("N_JD_Button")
        self.N_JD_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(5))
        self.N_Munich_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Munich_Teaser.setGeometry(QtCore.QRect(20, 2230, 901, 71))
        self.N_Munich_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_Munich_Teaser.setObjectName("N_Munich_Teaser")
        self.N_HSV_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_HSV_Teaser.setGeometry(QtCore.QRect(20, 3310, 901, 81))
        self.N_HSV_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_HSV_Teaser.setObjectName("N_HSV_Teaser")
        self.N_Munich_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Munich_Pic.setGeometry(QtCore.QRect(20, 1790, 901, 361))
        self.N_Munich_Pic.setText("")
        self.N_Munich_Pic.setPixmap(QtGui.QPixmap("schloss.bmp"))
        self.N_Munich_Pic.setScaledContents(True)
        self.N_Munich_Pic.setObjectName("N_Munich_Pic")
        self.N_Merkel_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Merkel_Head.setGeometry(QtCore.QRect(20, 590, 901, 51))
        self.N_Merkel_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;\n"
"\n"
"")
        self.N_Merkel_Head.setObjectName("N_Merkel_Head")
        self.N_GoT_Pic = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_GoT_Pic.setGeometry(QtCore.QRect(20, 2320, 901, 361))
        self.N_GoT_Pic.setText("")
        self.N_GoT_Pic.setPixmap(QtGui.QPixmap("got2.bmp"))
        self.N_GoT_Pic.setScaledContents(True)
        self.N_GoT_Pic.setObjectName("N_GoT_Pic")
        self.N_Top_Date = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Top_Date.setGeometry(QtCore.QRect(680, 150, 241, 51))
        self.N_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.N_Top_Date.setObjectName("N_Top_Date")
        self.N_HSV_Head = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_HSV_Head.setGeometry(QtCore.QRect(20, 3260, 901, 51))
        self.N_HSV_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.N_HSV_Head.setObjectName("N_HSV_Head")
        self.N_Acc_Teaser = QtWidgets.QLabel(self.N_scrollAreaWidgetContents)
        self.N_Acc_Teaser.setGeometry(QtCore.QRect(20, 1150, 901, 71))
        self.N_Acc_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.N_Acc_Teaser.setObjectName("N_Acc_Teaser")
        self.N_HSV_Pic.raise_()
        self.N_Acc_Head.raise_()
        self.N_JD_Teaser.raise_()
        self.N_JD_Pic.raise_()
        self.N_Trump_Pic.raise_()
        self.N_Munich_Head.raise_()
        self.N_Trump_Head.raise_()
        self.N_Trump_Teaser.raise_()
        self.N_GoT_Head.raise_()
        self.N_Bottom.raise_()
        self.N_Acc_Pic.raise_()
        self.N_GoT_Teaser.raise_()
        self.N_Merkel_Pic.raise_()
        self.N_Merkel_Teaser.raise_()
        self.N_Top_Head.raise_()
        self.N_JD_Head.raise_()
        self.N_Munich_Teaser.raise_()
        self.N_HSV_Teaser.raise_()
        self.N_Munich_Pic.raise_()
        self.N_Merkel_Head.raise_()
        self.N_GoT_Pic.raise_()
        self.N_Top_Date.raise_()
        self.N_HSV_Head.raise_()
        self.N_Acc_Teaser.raise_()
        self.N_Merkel_Button.raise_()
        self.N_Acc_Button.raise_()
        self.N_JD_Button.raise_()
        self.N_Munich_Button.raise_()
        self.N_GoT_Button.raise_()
        self.N_HSV_Button.raise_()
        self.N_Trump_Button.raise_()
        self.N_scrollArea.setWidget(self.N_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.News)
        self.GoT = QtWidgets.QWidget()
        self.GoT.setObjectName("GoT")
        self.GoT_scrollArea = QtWidgets.QScrollArea(self.GoT)
        self.GoT_scrollArea.setGeometry(QtCore.QRect(20, 10, 931, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.GoT_scrollArea.setWidgetResizable(False)
        self.GoT_scrollArea.setObjectName("GoT_scrollArea")
        self.GoT_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.GoT_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 931, 1900))
        self.GoT_scrollAreaWidgetContents.setObjectName("GoT_scrollAreaWidgetContents")
        self.GoT_HSV_Pic = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_HSV_Pic.setGeometry(QtCore.QRect(0, 1540, 400, 160))
        self.GoT_HSV_Pic.setText("")
        self.GoT_HSV_Pic.setPixmap(QtGui.QPixmap("ronaldo.bmp"))
        self.GoT_HSV_Pic.setScaledContents(True)
        self.GoT_HSV_Pic.setObjectName("GoT_HSV_Pic")
        self.GoT_Pic = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.GoT_Pic.setText("")
        self.GoT_Pic.setPixmap(QtGui.QPixmap("SWgot2.bmp"))
        self.GoT_Pic.setScaledContents(True)
        self.GoT_Pic.setObjectName("GoT_Pic")
        self.GoT_Ad = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Ad.setGeometry(QtCore.QRect(0, 1070, 221, 21))
        self.GoT_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.GoT_Ad.setObjectName("GoT_Ad")
        self.GoT_JD_Head = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_JD_Head.setGeometry(QtCore.QRect(440, 1140, 441, 141))
        self.GoT_JD_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.GoT_JD_Head.setObjectName("GoT_JD_Head")
        self.GoT_Top_Date = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Top_Date.setGeometry(QtCore.QRect(660, 140, 241, 51))
        self.GoT_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.GoT_Top_Date.setObjectName("GoT_Top_Date")
        self.GoT_JD_Button = QtWidgets.QPushButton(self.GoT_scrollAreaWidgetContents)
        self.GoT_JD_Button.setGeometry(QtCore.QRect(790, 1190, 93, 28))
        self.GoT_JD_Button.setObjectName("GoT_JD_Button")
        self.GoT_JD_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(5))
        self.GoT_Home_Button = QtWidgets.QPushButton(self.GoT_scrollAreaWidgetContents)
        self.GoT_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.GoT_Home_Button.setObjectName("GoT_Home_Button")
        self.GoT_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.GoT_Munich_Pic = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Munich_Pic.setGeometry(QtCore.QRect(0, 1340, 400, 160))
        self.GoT_Munich_Pic.setText("")
        self.GoT_Munich_Pic.setPixmap(QtGui.QPixmap("schloss.bmp"))
        self.GoT_Munich_Pic.setScaledContents(True)
        self.GoT_Munich_Pic.setObjectName("GoT_Munich_Pic")
        self.GoT_Teaser = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 91))
        self.GoT_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.GoT_Teaser.setObjectName("GoT_Teaser")
        self.GoT_Top_Head = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.GoT_Top_Head.setAutoFillBackground(False)
        self.GoT_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.GoT_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.GoT_Top_Head.setWordWrap(False)
        self.GoT_Top_Head.setObjectName("GoT_Top_Head")
        self.GoT_HSV_Head = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_HSV_Head.setGeometry(QtCore.QRect(440, 1550, 441, 141))
        self.GoT_HSV_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.GoT_HSV_Head.setObjectName("GoT_HSV_Head")
        self.GoT_Munich_Head = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Munich_Head.setGeometry(QtCore.QRect(440, 1350, 441, 141))
        self.GoT_Munich_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.GoT_Munich_Head.setObjectName("GoT_Munich_Head")
        self.GoT_Munich_Button = QtWidgets.QPushButton(self.GoT_scrollAreaWidgetContents)
        self.GoT_Munich_Button.setGeometry(QtCore.QRect(790, 1400, 93, 28))
        self.GoT_Munich_Button.setObjectName("GoT_Munich_Button")
        self.GoT_Munich_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(6))
        self.GoT_HSV_Button = QtWidgets.QPushButton(self.GoT_scrollAreaWidgetContents)
        self.GoT_HSV_Button.setGeometry(QtCore.QRect(790, 1600, 93, 28))
        self.GoT_HSV_Button.setObjectName("GoT_HSV_Button")
        self.GoT_HSV_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(2))
        self.GoT_JD_Pic = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_JD_Pic.setGeometry(QtCore.QRect(0, 1140, 400, 160))
        self.GoT_JD_Pic.setText("")
        self.GoT_JD_Pic.setPixmap(QtGui.QPixmap("johnny-depp.bmp"))
        self.GoT_JD_Pic.setScaledContents(True)
        self.GoT_JD_Pic.setObjectName("GoT_JD_Pic")
        self.GoT_Head = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Head.setGeometry(QtCore.QRect(0, 610, 891, 51))
        self.GoT_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;\n"
"")
        self.GoT_Head.setObjectName("GoT_Head")
        self.GoT_Text = QtWidgets.QLabel(self.GoT_scrollAreaWidgetContents)
        self.GoT_Text.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.GoT_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.GoT_Text.setObjectName("GoT_Text")
        self.GoT_HSV_Pic.raise_()
        self.GoT_Pic.raise_()
        self.GoT_Ad.raise_()
        self.GoT_JD_Head.raise_()
        self.GoT_Top_Date.raise_()
        self.GoT_Munich_Pic.raise_()
        self.GoT_Teaser.raise_()
        self.GoT_Top_Head.raise_()
        self.GoT_HSV_Head.raise_()
        self.GoT_Munich_Head.raise_()
        self.GoT_JD_Pic.raise_()
        self.GoT_Head.raise_()
        self.GoT_Text.raise_()
        self.GoT_Home_Button.raise_()
        self.GoT_HSV_Button.raise_()
        self.GoT_Munich_Button.raise_()
        self.GoT_JD_Button.raise_()
        self.GoT_scrollArea.setWidget(self.GoT_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.GoT)
        self.HSV = QtWidgets.QWidget()
        self.HSV.setObjectName("HSV")
        self.HSV_scrollArea = QtWidgets.QScrollArea(self.HSV)
        self.HSV_scrollArea.setGeometry(QtCore.QRect(20, 10, 931, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.HSV_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.HSV_scrollArea.setWidgetResizable(False)
        self.HSV_scrollArea.setObjectName("HSV_scrollArea")
        self.HSV_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.HSV_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 931, 1900))
        self.HSV_scrollAreaWidgetContents.setObjectName("HSV_scrollAreaWidgetContents")
        self.HSV_Head = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Head.setGeometry(QtCore.QRect(0, 610, 891, 51))
        self.HSV_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;\n"
"")
        self.HSV_Head.setObjectName("HSV_Head")
        self.HSV_JD_Button = QtWidgets.QPushButton(self.HSV_scrollAreaWidgetContents)
        self.HSV_JD_Button.setGeometry(QtCore.QRect(800, 1400, 93, 28))
        self.HSV_JD_Button.setObjectName("HSV_JD_Button")
        self.HSV_JD_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(5))
        self.HSV_Pic = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.HSV_Pic.setText("")
        self.HSV_Pic.setPixmap(QtGui.QPixmap("SWronaldo.bmp"))
        self.HSV_Pic.setObjectName("HSV_Pic")
        self.HSV_Home_Button = QtWidgets.QPushButton(self.HSV_scrollAreaWidgetContents)
        self.HSV_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.HSV_Home_Button.setObjectName("HSV_Home_Button")
        self.HSV_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.HSV_Trump_Button = QtWidgets.QPushButton(self.HSV_scrollAreaWidgetContents)
        self.HSV_Trump_Button.setGeometry(QtCore.QRect(800, 1200, 93, 28))
        self.HSV_Trump_Button.setObjectName("HSV_Trump_Button")
        self.HSV_Trump_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(4))
        self.HSV_JD_Pic = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_JD_Pic.setGeometry(QtCore.QRect(0, 1330, 400, 160))
        self.HSV_JD_Pic.setText("")
        self.HSV_JD_Pic.setPixmap(QtGui.QPixmap("johnny-depp.bmp"))
        self.HSV_JD_Pic.setScaledContents(True)
        self.HSV_JD_Pic.setObjectName("HSV_JD_Pic")
        self.HSV_Trump_Pic = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Trump_Pic.setGeometry(QtCore.QRect(0, 1140, 400, 160))
        self.HSV_Trump_Pic.setText("")
        self.HSV_Trump_Pic.setPixmap(QtGui.QPixmap("trumptwitter.bmp"))
        self.HSV_Trump_Pic.setScaledContents(True)
        self.HSV_Trump_Pic.setObjectName("HSV_Trump_Pic")
        self.HSV_JD_Head = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_JD_Head.setGeometry(QtCore.QRect(440, 1340, 441, 141))
        self.HSV_JD_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.HSV_JD_Head.setObjectName("HSV_JD_Head")
        self.HSV_Top_Head = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.HSV_Top_Head.setAutoFillBackground(False)
        self.HSV_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.HSV_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.HSV_Top_Head.setWordWrap(False)
        self.HSV_Top_Head.setObjectName("HSV_Top_Head")
        self.HSV_GoT_Pic = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_GoT_Pic.setGeometry(QtCore.QRect(0, 1520, 400, 160))
        self.HSV_GoT_Pic.setText("")
        self.HSV_GoT_Pic.setPixmap(QtGui.QPixmap("got2.bmp"))
        self.HSV_GoT_Pic.setScaledContents(True)
        self.HSV_GoT_Pic.setObjectName("HSV_GoT_Pic")
        self.HSV_Top_Date = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Top_Date.setGeometry(QtCore.QRect(660, 140, 241, 51))
        self.HSV_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.HSV_Top_Date.setObjectName("HSV_Top_Date")
        self.HSV_Ad = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Ad.setGeometry(QtCore.QRect(0, 1070, 221, 21))
        self.HSV_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.HSV_Ad.setObjectName("HSV_Ad")
        self.HSV_Teaser = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 91))
        self.HSV_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.HSV_Teaser.setObjectName("HSV_Teaser")
        self.HSV_GoT_Head = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_GoT_Head.setGeometry(QtCore.QRect(440, 1530, 441, 141))
        self.HSV_GoT_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.HSV_GoT_Head.setObjectName("HSV_GoT_Head")
        self.HSV_GoT_Button = QtWidgets.QPushButton(self.HSV_scrollAreaWidgetContents)
        self.HSV_GoT_Button.setGeometry(QtCore.QRect(800, 1580, 93, 28))
        self.HSV_GoT_Button.setObjectName("HSV_GoT_Button")
        self.HSV_GoT_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(1))
        self.HSV_Text = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Text.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.HSV_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.HSV_Text.setObjectName("HSV_Text")
        self.HSV_Trump_Head = QtWidgets.QLabel(self.HSV_scrollAreaWidgetContents)
        self.HSV_Trump_Head.setGeometry(QtCore.QRect(430, 1140, 441, 141))
        self.HSV_Trump_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.HSV_Trump_Head.setObjectName("HSV_Trump_Head")
        self.HSV_Head.raise_()
        self.HSV_Pic.raise_()
        self.HSV_JD_Pic.raise_()
        self.HSV_Trump_Pic.raise_()
        self.HSV_JD_Head.raise_()
        self.HSV_Top_Head.raise_()
        self.HSV_GoT_Pic.raise_()
        self.HSV_Top_Date.raise_()
        self.HSV_Ad.raise_()
        self.HSV_Teaser.raise_()
        self.HSV_GoT_Head.raise_()
        self.HSV_Text.raise_()
        self.HSV_Trump_Head.raise_()
        self.HSV_Home_Button.raise_()
        self.HSV_Trump_Button.raise_()
        self.HSV_JD_Button.raise_()
        self.HSV_GoT_Button.raise_()
        self.HSV_scrollArea.setWidget(self.HSV_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.HSV)
        self.Accident = QtWidgets.QWidget()
        self.Accident.setObjectName("Accident")
        self.Acc_scrollArea = QtWidgets.QScrollArea(self.Accident)
        self.Acc_scrollArea.setGeometry(QtCore.QRect(0, 0, 951, 1000))
        self.Acc_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Acc_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Acc_scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Acc_scrollArea.setWidgetResizable(False)
        self.Acc_scrollArea.setObjectName("Acc_scrollArea")
        self.Acc_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Acc_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 1900))
        self.Acc_scrollAreaWidgetContents.setObjectName("Acc_scrollAreaWidgetContents")
        self.Acc_HSV_Head = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_HSV_Head.setGeometry(QtCore.QRect(440, 1350, 441, 141))
        self.Acc_HSV_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Acc_HSV_Head.setObjectName("Acc_HSV_Head")
        self.Acc_Merkel_Button = QtWidgets.QPushButton(self.Acc_scrollAreaWidgetContents)
        self.Acc_Merkel_Button.setGeometry(QtCore.QRect(790, 1210, 93, 28))
        self.Acc_Merkel_Button.setObjectName("Acc_Merkel_Button")
        self.Acc_Merkel_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(7))
        self.Acc_HSV_Button = QtWidgets.QPushButton(self.Acc_scrollAreaWidgetContents)
        self.Acc_HSV_Button.setGeometry(QtCore.QRect(790, 1410, 93, 28))
        self.Acc_HSV_Button.setObjectName("Acc_HSV_Button")
        self.Acc_HSV_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(2))
        self.Acc_Merkel_Pic = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Merkel_Pic.setGeometry(QtCore.QRect(20, 1140, 400, 160))
        self.Acc_Merkel_Pic.setText("")
        self.Acc_Merkel_Pic.setPixmap(QtGui.QPixmap("angela-merkel-barack-obama-berlin.bmp"))
        self.Acc_Merkel_Pic.setScaledContents(True)
        self.Acc_Merkel_Pic.setObjectName("Acc_Merkel_Pic")
        self.Acc_Ad = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Ad.setGeometry(QtCore.QRect(20, 1070, 221, 21))
        self.Acc_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.Acc_Ad.setObjectName("Acc_Ad")
        self.Acc_Head = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Head.setGeometry(QtCore.QRect(20, 610, 901, 51))
        self.Acc_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.Acc_Head.setObjectName("Acc_Head")
        self.Acc_Trump_Button = QtWidgets.QPushButton(self.Acc_scrollAreaWidgetContents)
        self.Acc_Trump_Button.setGeometry(QtCore.QRect(790, 1600, 93, 28))
        self.Acc_Trump_Button.setObjectName("Acc_Trump_Button")
        self.Acc_Trump_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(4))
        self.Acc_Text = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Text.setGeometry(QtCore.QRect(20, 760, 901, 81))
        self.Acc_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.Acc_Text.setObjectName("Acc_Text")
        self.Acc_HSV_Pic = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_HSV_Pic.setGeometry(QtCore.QRect(20, 1340, 400, 160))
        self.Acc_HSV_Pic.setText("")
        self.Acc_HSV_Pic.setPixmap(QtGui.QPixmap("ronaldo.bmp"))
        self.Acc_HSV_Pic.setScaledContents(True)
        self.Acc_HSV_Pic.setObjectName("Acc_HSV_Pic")
        self.Acc_Trump_Pic = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Trump_Pic.setGeometry(QtCore.QRect(20, 1540, 400, 160))
        self.Acc_Trump_Pic.setText("")
        self.Acc_Trump_Pic.setPixmap(QtGui.QPixmap("trumptwitter.bmp"))
        self.Acc_Trump_Pic.setScaledContents(True)
        self.Acc_Trump_Pic.setObjectName("Acc_Trump_Pic")
        self.Acc_Merkel_Head = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Merkel_Head.setGeometry(QtCore.QRect(440, 1150, 441, 141))
        self.Acc_Merkel_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Acc_Merkel_Head.setObjectName("Acc_Merkel_Head")
        self.Acc_Pic = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Pic.setGeometry(QtCore.QRect(20, 200, 911, 381))
        self.Acc_Pic.setText("")
        self.Acc_Pic.setPixmap(QtGui.QPixmap("SWautounfall.bmp"))
        self.Acc_Pic.setScaledContents(True)
        self.Acc_Pic.setObjectName("Acc_Pic")
        self.Acc_Top_Head = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.Acc_Top_Head.setAutoFillBackground(False)
        self.Acc_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.Acc_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.Acc_Top_Head.setWordWrap(False)
        self.Acc_Top_Head.setObjectName("Acc_Top_Head")
        self.Acc_Top_Date = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Top_Date.setGeometry(QtCore.QRect(660, 140, 241, 51))
        self.Acc_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.Acc_Top_Date.setObjectName("Acc_Top_Date")
        self.Acc_Trump_Head = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Trump_Head.setGeometry(QtCore.QRect(440, 1550, 441, 141))
        self.Acc_Trump_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Acc_Trump_Head.setObjectName("Acc_Trump_Head")
        self.Acc_Home_Button = QtWidgets.QPushButton(self.Acc_scrollAreaWidgetContents)
        self.Acc_Home_Button.setGeometry(QtCore.QRect(20, 170, 93, 28))
        self.Acc_Home_Button.setObjectName("Acc_Home_Button")
        self.Acc_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.Acc_Teaser = QtWidgets.QLabel(self.Acc_scrollAreaWidgetContents)
        self.Acc_Teaser.setGeometry(QtCore.QRect(20, 670, 901, 71))
        self.Acc_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.Acc_Teaser.setObjectName("Acc_Teaser")
        self.Acc_HSV_Head.raise_()
        self.Acc_Merkel_Pic.raise_()
        self.Acc_Ad.raise_()
        self.Acc_Head.raise_()
        self.Acc_Text.raise_()
        self.Acc_HSV_Pic.raise_()
        self.Acc_Trump_Pic.raise_()
        self.Acc_Merkel_Head.raise_()
        self.Acc_Pic.raise_()
        self.Acc_Top_Head.raise_()
        self.Acc_Top_Date.raise_()
        self.Acc_Trump_Head.raise_()
        self.Acc_Teaser.raise_()
        self.Acc_Home_Button.raise_()
        self.Acc_Merkel_Button.raise_()
        self.Acc_HSV_Button.raise_()
        self.Acc_Trump_Button.raise_()
        self.Acc_scrollArea.setWidget(self.Acc_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.Accident)
        self.Trump = QtWidgets.QWidget()
        self.Trump.setObjectName("Trump")
        self.Trump_scrollArea = QtWidgets.QScrollArea(self.Trump)
        self.Trump_scrollArea.setGeometry(QtCore.QRect(20, 10, 951, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Trump_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Trump_scrollArea.setWidgetResizable(False)
        self.Trump_scrollArea.setObjectName("Trump_scrollArea")
        self.Trump_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Trump_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 1900))
        self.Trump_scrollAreaWidgetContents.setObjectName("Trump_scrollAreaWidgetContents")
        self.Trump_Head = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Head.setGeometry(QtCore.QRect(0, 610, 901, 51))
        self.Trump_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.Trump_Head.setObjectName("Trump_Head")
        self.Trump_Teaser = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 81))
        self.Trump_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.Trump_Teaser.setObjectName("Trump_Teaser")
        self.Trump_Munich_Pic = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Munich_Pic.setGeometry(QtCore.QRect(0, 1330, 400, 160))
        self.Trump_Munich_Pic.setText("")
        self.Trump_Munich_Pic.setPixmap(QtGui.QPixmap("schloss.bmp"))
        self.Trump_Munich_Pic.setScaledContents(True)
        self.Trump_Munich_Pic.setObjectName("Trump_Munich_Pic")
        self.Trump_HSV_Head = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_HSV_Head.setGeometry(QtCore.QRect(440, 1150, 441, 141))
        self.Trump_HSV_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Trump_HSV_Head.setObjectName("Trump_HSV_Head")
        self.Trump_Munich_Button = QtWidgets.QPushButton(self.Trump_scrollAreaWidgetContents)
        self.Trump_Munich_Button.setGeometry(QtCore.QRect(820, 1400, 93, 28))
        self.Trump_Munich_Button.setObjectName("Trump_Munich_Button")
        self.Trump_Munich_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(6))
        self.Trump_Pic = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.Trump_Pic.setText("")
        self.Trump_Pic.setPixmap(QtGui.QPixmap("SWtrumptwitter.bmp"))
        self.Trump_Pic.setScaledContents(True)
        self.Trump_Pic.setObjectName("Trump_Pic")
        self.Trump_Home_Button = QtWidgets.QPushButton(self.Trump_scrollAreaWidgetContents)
        self.Trump_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.Trump_Home_Button.setObjectName("Trump_Home_Button")
        self.Trump_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.Trump_Text = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Text.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.Trump_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.Trump_Text.setObjectName("Trump_Text")
        self.Trump_HSV_Button = QtWidgets.QPushButton(self.Trump_scrollAreaWidgetContents)
        self.Trump_HSV_Button.setGeometry(QtCore.QRect(820, 1210, 93, 28))
        self.Trump_HSV_Button.setObjectName("Trump_HSV_Button")
        self.Trump_HSV_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(2))
        self.Trump_Merkel_Pic = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Merkel_Pic.setGeometry(QtCore.QRect(0, 1510, 400, 160))
        self.Trump_Merkel_Pic.setText("")
        self.Trump_Merkel_Pic.setPixmap(QtGui.QPixmap("angela-merkel-barack-obama-berlin.bmp"))
        self.Trump_Merkel_Pic.setScaledContents(True)
        self.Trump_Merkel_Pic.setObjectName("Trump_Merkel_Pic")
        self.Trump_Ad = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Ad.setGeometry(QtCore.QRect(10, 1080, 221, 21))
        self.Trump_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.Trump_Ad.setObjectName("Trump_Ad")
        self.Trump_Merkel_Button = QtWidgets.QPushButton(self.Trump_scrollAreaWidgetContents)
        self.Trump_Merkel_Button.setGeometry(QtCore.QRect(820, 1570, 93, 28))
        self.Trump_Merkel_Button.setObjectName("Trump_Merkel_Button")
        self.Trump_Merkel_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(7))
        self.Trump_Top_Date = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Top_Date.setGeometry(QtCore.QRect(660, 140, 241, 51))
        self.Trump_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.Trump_Top_Date.setObjectName("Trump_Top_Date")
        self.Trump_Merkel_Head = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Merkel_Head.setGeometry(QtCore.QRect(430, 1520, 441, 141))
        self.Trump_Merkel_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Trump_Merkel_Head.setObjectName("Trump_Merkel_Head")
        self.Trump_Top_Head = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.Trump_Top_Head.setAutoFillBackground(False)
        self.Trump_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.Trump_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.Trump_Top_Head.setWordWrap(False)
        self.Trump_Top_Head.setObjectName("Trump_Top_Head")
        self.Trump_Munich_Head = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_Munich_Head.setGeometry(QtCore.QRect(430, 1340, 441, 141))
        self.Trump_Munich_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Trump_Munich_Head.setObjectName("Trump_Munich_Head")
        self.Trump_HSV_Pic = QtWidgets.QLabel(self.Trump_scrollAreaWidgetContents)
        self.Trump_HSV_Pic.setGeometry(QtCore.QRect(0, 1140, 400, 160))
        self.Trump_HSV_Pic.setText("")
        self.Trump_HSV_Pic.setPixmap(QtGui.QPixmap("ronaldo.bmp"))
        self.Trump_HSV_Pic.setScaledContents(True)
        self.Trump_HSV_Pic.setObjectName("Trump_HSV_Pic")
        self.Trump_Head.raise_()
        self.Trump_Teaser.raise_()
        self.Trump_Munich_Pic.raise_()
        self.Trump_HSV_Head.raise_()
        self.Trump_Pic.raise_()
        self.Trump_Text.raise_()
        self.Trump_Merkel_Pic.raise_()
        self.Trump_Ad.raise_()
        self.Trump_Top_Date.raise_()
        self.Trump_Merkel_Head.raise_()
        self.Trump_Top_Head.raise_()
        self.Trump_Munich_Head.raise_()
        self.Trump_HSV_Pic.raise_()
        self.Trump_Home_Button.raise_()
        self.Trump_HSV_Button.raise_()
        self.Trump_Munich_Button.raise_()
        self.Trump_Merkel_Button.raise_()
        self.Trump_scrollArea.setWidget(self.Trump_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.Trump)
        self.JohnnyDepp = QtWidgets.QWidget()
        self.JohnnyDepp.setObjectName("JohnnyDepp")
        self.JD_scrollArea = QtWidgets.QScrollArea(self.JohnnyDepp)
        self.JD_scrollArea.setGeometry(QtCore.QRect(20, 10, 951, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.JD_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.JD_scrollArea.setWidgetResizable(False)
        self.JD_scrollArea.setObjectName("JD_scrollArea")
        self.JD_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.JD_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 1900))
        self.JD_scrollAreaWidgetContents.setObjectName("JD_scrollAreaWidgetContents")
        self.JD_GoT_Button = QtWidgets.QPushButton(self.JD_scrollAreaWidgetContents)
        self.JD_GoT_Button.setGeometry(QtCore.QRect(770, 1590, 93, 28))
        self.JD_GoT_Button.setObjectName("JD_GoT_Button")
        self.JD_GoT_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(1))
        self.JD_Top_Head = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.JD_Top_Head.setAutoFillBackground(False)
        self.JD_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.JD_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.JD_Top_Head.setWordWrap(False)
        self.JD_Top_Head.setObjectName("JD_Top_Head")
        self.JD_Ad = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Ad.setGeometry(QtCore.QRect(0, 1070, 221, 21))
        self.JD_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.JD_Ad.setObjectName("JD_Ad")
        self.JD_Teaser = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 91))
        self.JD_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.JD_Teaser.setObjectName("JD_Teaser")
        self.JD_GoT_Pic = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_GoT_Pic.setGeometry(QtCore.QRect(0, 1530, 400, 160))
        self.JD_GoT_Pic.setText("")
        self.JD_GoT_Pic.setPixmap(QtGui.QPixmap("got2.bmp"))
        self.JD_GoT_Pic.setScaledContents(True)
        self.JD_GoT_Pic.setObjectName("JD_GoT_Pic")
        self.JD_Head = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Head.setGeometry(QtCore.QRect(0, 610, 891, 51))
        self.JD_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;\n"
"")
        self.JD_Head.setObjectName("JD_Head")
        self.JD_Munich_Pic = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Munich_Pic.setGeometry(QtCore.QRect(0, 1140, 400, 160))
        self.JD_Munich_Pic.setText("")
        self.JD_Munich_Pic.setPixmap(QtGui.QPixmap("schloss.bmp"))
        self.JD_Munich_Pic.setScaledContents(True)
        self.JD_Munich_Pic.setObjectName("JD_Munich_Pic")
        self.JD_Teaser_2 = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Teaser_2.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.JD_Teaser_2.setStyleSheet("font: 11pt \"Arial\";")
        self.JD_Teaser_2.setObjectName("JD_Teaser_2")
        self.JD_Merkel_Button = QtWidgets.QPushButton(self.JD_scrollAreaWidgetContents)
        self.JD_Merkel_Button.setGeometry(QtCore.QRect(770, 1390, 93, 28))
        self.JD_Merkel_Button.setObjectName("JD_Merkel_Button")
        self.JD_Merkel_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(7))
        self.JD_Merkel_Pic = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Merkel_Pic.setGeometry(QtCore.QRect(0, 1330, 400, 160))
        self.JD_Merkel_Pic.setText("")
        self.JD_Merkel_Pic.setPixmap(QtGui.QPixmap("angela-merkel-barack-obama-berlin.bmp"))
        self.JD_Merkel_Pic.setScaledContents(True)
        self.JD_Merkel_Pic.setObjectName("JD_Merkel_Pic")
        self.JD_Merkel_Head = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Merkel_Head.setGeometry(QtCore.QRect(430, 1340, 441, 141))
        self.JD_Merkel_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.JD_Merkel_Head.setObjectName("JD_Merkel_Head")
        self.JD_Pic = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.JD_Pic.setText("")
        self.JD_Pic.setPixmap(QtGui.QPixmap("SWjohnny-depp.bmp"))
        self.JD_Pic.setObjectName("JD_Pic")
        self.JD_Munich_Head = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Munich_Head.setGeometry(QtCore.QRect(430, 1140, 441, 141))
        self.JD_Munich_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.JD_Munich_Head.setObjectName("JD_Munich_Head")
        self.JD_Top_Date = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_Top_Date.setGeometry(QtCore.QRect(660, 140, 251, 51))
        self.JD_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.JD_Top_Date.setObjectName("JD_Top_Date")
        self.JD_GoT_Head = QtWidgets.QLabel(self.JD_scrollAreaWidgetContents)
        self.JD_GoT_Head.setGeometry(QtCore.QRect(430, 1540, 441, 141))
        self.JD_GoT_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.JD_GoT_Head.setObjectName("JD_GoT_Head")
        self.JD_Munich_Button = QtWidgets.QPushButton(self.JD_scrollAreaWidgetContents)
        self.JD_Munich_Button.setGeometry(QtCore.QRect(770, 1190, 93, 28))
        self.JD_Munich_Button.setObjectName("JD_Munich_Button")
        self.JD_Munich_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(6))
        self.JD_Home_Button = QtWidgets.QPushButton(self.JD_scrollAreaWidgetContents)
        self.JD_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.JD_Home_Button.setObjectName("JD_Home_Button")
        self.JD_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.JD_GoT_Head.raise_()
        self.JD_Merkel_Head.raise_()
        self.JD_Top_Head.raise_()
        self.JD_Ad.raise_()
        self.JD_Teaser.raise_()
        self.JD_GoT_Pic.raise_()
        self.JD_Head.raise_()
        self.JD_Munich_Pic.raise_()
        self.JD_Teaser_2.raise_()
        self.JD_Merkel_Pic.raise_()
        self.JD_Pic.raise_()
        self.JD_Munich_Head.raise_()
        self.JD_Top_Date.raise_()
        self.JD_Home_Button.raise_()
        self.JD_Munich_Button.raise_()
        self.JD_Merkel_Button.raise_()
        self.JD_GoT_Button.raise_()
        self.JD_scrollArea.setWidget(self.JD_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.JohnnyDepp)
        self.Munich = QtWidgets.QWidget()
        self.Munich.setObjectName("Munich")
        self.Munich_scrollArea = QtWidgets.QScrollArea(self.Munich)
        self.Munich_scrollArea.setGeometry(QtCore.QRect(20, 10, 951, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Munich_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Munich_scrollArea.setWidgetResizable(False)
        self.Munich_scrollArea.setObjectName("Munich_scrollArea")
        self.Munich_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Munich_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 1900))
        self.Munich_scrollAreaWidgetContents.setObjectName("Munich_scrollAreaWidgetContents")
        self.Munich_Pic = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.Munich_Pic.setText("")
        self.Munich_Pic.setPixmap(QtGui.QPixmap("SWschloss.bmp"))
        self.Munich_Pic.setScaledContents(True)
        self.Munich_Pic.setObjectName("Munich_Pic")
        self.Munich_GoT_Head = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_GoT_Head.setGeometry(QtCore.QRect(440, 1530, 441, 141))
        self.Munich_GoT_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Munich_GoT_Head.setObjectName("Munich_GoT_Head")
        self.Munich_Home_Button = QtWidgets.QPushButton(self.Munich_scrollAreaWidgetContents)
        self.Munich_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.Munich_Home_Button.setObjectName("Munich_Home_Button")
        self.Munich_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.Munich_Merkel_Head = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Merkel_Head.setGeometry(QtCore.QRect(450, 1150, 441, 141))
        self.Munich_Merkel_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Munich_Merkel_Head.setObjectName("Munich_Merkel_Head")
        self.Munich_GoT_Pic = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_GoT_Pic.setGeometry(QtCore.QRect(0, 1520, 400, 160))
        self.Munich_GoT_Pic.setText("")
        self.Munich_GoT_Pic.setPixmap(QtGui.QPixmap("got2.bmp"))
        self.Munich_GoT_Pic.setScaledContents(True)
        self.Munich_GoT_Pic.setObjectName("Munich_GoT_Pic")
        self.Munich_Merkel_Pic = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Merkel_Pic.setGeometry(QtCore.QRect(0, 1140, 400, 160))
        self.Munich_Merkel_Pic.setText("")
        self.Munich_Merkel_Pic.setPixmap(QtGui.QPixmap("angela-merkel-barack-obama-berlin.bmp"))
        self.Munich_Merkel_Pic.setScaledContents(True)
        self.Munich_Merkel_Pic.setObjectName("Munich_Merkel_Pic")
        self.Munich_Trump_Head = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Trump_Head.setGeometry(QtCore.QRect(450, 1330, 441, 141))
        self.Munich_Trump_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Munich_Trump_Head.setObjectName("Munich_Trump_Head")
        self.Munich_Trump_Pic = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Trump_Pic.setGeometry(QtCore.QRect(0, 1330, 400, 160))
        self.Munich_Trump_Pic.setText("")
        self.Munich_Trump_Pic.setPixmap(QtGui.QPixmap("trumptwitter.bmp"))
        self.Munich_Trump_Pic.setScaledContents(True)
        self.Munich_Trump_Pic.setObjectName("Munich_Trump_Pic")
        self.Munich_GoT_Button = QtWidgets.QPushButton(self.Munich_scrollAreaWidgetContents)
        self.Munich_GoT_Button.setGeometry(QtCore.QRect(790, 1590, 93, 28))
        self.Munich_GoT_Button.setObjectName("Munich_GoT_Button")
        self.Munich_GoT_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(1))
        self.Munich_Merkel_Button = QtWidgets.QPushButton(self.Munich_scrollAreaWidgetContents)
        self.Munich_Merkel_Button.setGeometry(QtCore.QRect(790, 1210, 93, 28))
        self.Munich_Merkel_Button.setObjectName("Munich_Merkel_Button")
        self.Munich_Merkel_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(7))
        self.Munich_Top_Date = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Top_Date.setGeometry(QtCore.QRect(660, 140, 251, 51))
        self.Munich_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.Munich_Top_Date.setObjectName("Munich_Top_Date")
        self.Munich_Ad = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Ad.setGeometry(QtCore.QRect(0, 1070, 221, 21))
        self.Munich_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.Munich_Ad.setObjectName("Munich_Ad")
        self.Munich_Head = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Head.setGeometry(QtCore.QRect(0, 610, 901, 51))
        self.Munich_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;")
        self.Munich_Head.setObjectName("Munich_Head")
        self.Munich_Top_Head = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.Munich_Top_Head.setAutoFillBackground(False)
        self.Munich_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.Munich_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.Munich_Top_Head.setWordWrap(False)
        self.Munich_Top_Head.setObjectName("Munich_Top_Head")
        self.Munich_Teaser = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 71))
        self.Munich_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.Munich_Teaser.setObjectName("Munich_Teaser")
        self.Munich_Text = QtWidgets.QLabel(self.Munich_scrollAreaWidgetContents)
        self.Munich_Text.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.Munich_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.Munich_Text.setObjectName("Munich_Text")
        self.Munich_Trump_Button = QtWidgets.QPushButton(self.Munich_scrollAreaWidgetContents)
        self.Munich_Trump_Button.setGeometry(QtCore.QRect(790, 1390, 93, 28))
        self.Munich_Trump_Button.setObjectName("Munich_Trump_Button")
        self.Munich_Trump_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(4))
        self.Munich_Pic.raise_()
        self.Munich_GoT_Head.raise_()
        self.Munich_Merkel_Head.raise_()
        self.Munich_GoT_Pic.raise_()
        self.Munich_Merkel_Pic.raise_()
        self.Munich_Trump_Head.raise_()
        self.Munich_Trump_Pic.raise_()
        self.Munich_Top_Date.raise_()
        self.Munich_Ad.raise_()
        self.Munich_Head.raise_()
        self.Munich_Top_Head.raise_()
        self.Munich_Teaser.raise_()
        self.Munich_Text.raise_()
        self.Munich_Home_Button.raise_()
        self.Munich_Merkel_Button.raise_()
        self.Munich_Trump_Button.raise_()
        self.Munich_GoT_Button.raise_()
        self.Munich_scrollArea.setWidget(self.Munich_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.Munich)
        self.Merkel = QtWidgets.QWidget()
        self.Merkel.setObjectName("Merkel")
        self.Merkel_scrollArea = QtWidgets.QScrollArea(self.Merkel)
        self.Merkel_scrollArea.setGeometry(QtCore.QRect(20, 10, 951, 1000))
        self.GoT_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.GoT_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Merkel_scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Merkel_scrollArea.setWidgetResizable(False)
        self.Merkel_scrollArea.setObjectName("Merkel_scrollArea")
        self.Merkel_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.Merkel_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 951, 1900))
        self.Merkel_scrollAreaWidgetContents.setObjectName("Merkel_scrollAreaWidgetContents")
        self.Merkel_Head = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Head.setGeometry(QtCore.QRect(0, 610, 891, 51))
        self.Merkel_Head.setStyleSheet("font: 24pt \"Arial\";\n"
"text-decoration: underline;\n"
"")
        self.Merkel_Head.setObjectName("Merkel_Head")
        self.Merkel_Teaser = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Teaser.setGeometry(QtCore.QRect(0, 670, 901, 91))
        self.Merkel_Teaser.setStyleSheet("font: 14pt \"Arial\";")
        self.Merkel_Teaser.setObjectName("Merkel_Teaser")
        self.Merkel_Ad = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Ad.setGeometry(QtCore.QRect(0, 1070, 221, 21))
        self.Merkel_Ad.setStyleSheet("font: 12pt \"Arial\";")
        self.Merkel_Ad.setObjectName("Merkel_Ad")
        self.Merkel_Text = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Text.setGeometry(QtCore.QRect(0, 760, 901, 81))
        self.Merkel_Text.setStyleSheet("font: 11pt \"Arial\";")
        self.Merkel_Text.setObjectName("Merkel_Text")
        self.Merkel_Munich_Head = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Munich_Head.setGeometry(QtCore.QRect(430, 1550, 441, 141))
        self.Merkel_Munich_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Merkel_Munich_Head.setObjectName("Merkel_Munich_Head")
        self.Merkel_Munich_Button = QtWidgets.QPushButton(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Munich_Button.setGeometry(QtCore.QRect(740, 1610, 93, 28))
        self.Merkel_Munich_Button.setObjectName("Merkel_Munich_Button")
        self.Merkel_Munich_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(6))
        self.Merkel_Top_Head = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Top_Head.setGeometry(QtCore.QRect(330, 0, 240, 152))
        self.Merkel_Top_Head.setAutoFillBackground(False)
        self.Merkel_Top_Head.setStyleSheet("font: italic 40pt \"Garamond\";")
        self.Merkel_Top_Head.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.Merkel_Top_Head.setWordWrap(False)
        self.Merkel_Top_Head.setObjectName("Merkel_Top_Head")
        self.Merkel_JD_Button = QtWidgets.QPushButton(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_JD_Button.setGeometry(QtCore.QRect(740, 1390, 93, 28))
        self.Merkel_JD_Button.setObjectName("Merkel_JD_Button")
        self.Merkel_JD_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(5))
        self.Merkel_Home_Button = QtWidgets.QPushButton(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Home_Button.setGeometry(QtCore.QRect(0, 170, 93, 28))
        self.Merkel_Home_Button.setObjectName("Merkel_Home_Button")
        self.Merkel_Home_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(0))
        self.Merkel_JD_Pic = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_JD_Pic.setGeometry(QtCore.QRect(0, 1330, 400, 160))
        self.Merkel_JD_Pic.setText("")
        self.Merkel_JD_Pic.setPixmap(QtGui.QPixmap("johnny-depp.bmp"))
        self.Merkel_JD_Pic.setScaledContents(True)
        self.Merkel_JD_Pic.setObjectName("Merkel_JD_Pic")
        self.Merkel_Top_Date = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Top_Date.setGeometry(QtCore.QRect(660, 140, 251, 51))
        self.Merkel_Top_Date.setStyleSheet("font: italic 16pt \"Garamond\";")
        self.Merkel_Top_Date.setObjectName("Merkel_Top_Date")
        self.Merkel_GoT_Button = QtWidgets.QPushButton(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_GoT_Button.setGeometry(QtCore.QRect(740, 1190, 93, 28))
        self.Merkel_GoT_Button.setObjectName("Merkel_GoT_Button")
        self.Merkel_GoT_Button.clicked.connect(lambda:StackedWidget.setCurrentIndex(1))
        self.Merkel_Munich_Pic = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Munich_Pic.setGeometry(QtCore.QRect(0, 1540, 400, 160))
        self.Merkel_Munich_Pic.setText("")
        self.Merkel_Munich_Pic.setPixmap(QtGui.QPixmap("schloss.bmp"))
        self.Merkel_Munich_Pic.setScaledContents(True)
        self.Merkel_Munich_Pic.setObjectName("Merkel_Munich_Pic")
        self.Merkel_JD_Head = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_JD_Head.setGeometry(QtCore.QRect(430, 1340, 441, 141))
        self.Merkel_JD_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Merkel_JD_Head.setObjectName("Merkel_JD_Head")
        self.Merkel_Pic = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_Pic.setGeometry(QtCore.QRect(0, 200, 911, 381))
        self.Merkel_Pic.setText("")
        self.Merkel_Pic.setPixmap(QtGui.QPixmap("SWangela-merkel-barack-obama-berlin.bmp"))
        self.Merkel_Pic.setObjectName("Merkel_Pic")
        self.Merkel_GoT_Head = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_GoT_Head.setGeometry(QtCore.QRect(430, 1130, 441, 141))
        self.Merkel_GoT_Head.setStyleSheet("font: 14pt \"Arial\";\n"
"text-decoration: underline;")
        self.Merkel_GoT_Head.setObjectName("Merkel_GoT_Head")
        self.Merkel_GoT_Pic = QtWidgets.QLabel(self.Merkel_scrollAreaWidgetContents)
        self.Merkel_GoT_Pic.setGeometry(QtCore.QRect(0, 1120, 400, 160))
        self.Merkel_GoT_Pic.setText("")
        self.Merkel_GoT_Pic.setPixmap(QtGui.QPixmap("got2.bmp"))
        self.Merkel_GoT_Pic.setScaledContents(True)
        self.Merkel_GoT_Pic.setObjectName("Merkel_GoT_Pic")
        self.Merkel_Munich_Head.raise_()
        self.Merkel_JD_Head.raise_()
        self.Merkel_GoT_Head.raise_()
        self.Merkel_Head.raise_()
        self.Merkel_Teaser.raise_()
        self.Merkel_Ad.raise_()
        self.Merkel_Text.raise_()
        self.Merkel_Top_Head.raise_()
        self.Merkel_JD_Pic.raise_()
        self.Merkel_Top_Date.raise_()
        self.Merkel_Munich_Pic.raise_()
        self.Merkel_Pic.raise_()
        self.Merkel_GoT_Pic.raise_()
        self.Merkel_Home_Button.raise_()
        self.Merkel_GoT_Button.raise_()
        self.Merkel_JD_Button.raise_()
        self.Merkel_Munich_Button.raise_()
        self.Merkel_scrollArea.setWidget(self.Merkel_scrollAreaWidgetContents)
        StackedWidget.addWidget(self.Merkel)

        self.retranslateUi(StackedWidget)
        StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StackedWidget)

    def retranslateUi(self, StackedWidget):
        _translate = QtCore.QCoreApplication.translate
        StackedWidget.setWindowTitle(_translate("StackedWidget", "StackedWidget"))
        self.N_Acc_Head.setText(_translate("StackedWidget", "Car accident causes trouble near Berlin"))
        self.N_JD_Teaser.setText(_translate("StackedWidget", "He has an idea, which might change the story of Hollywood. Is he a genius or a maniac?"))
        self.N_Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising"))
        self.N_Trump_Head.setText(_translate("StackedWidget", "Trump declares war via Twitter"))
        self.N_Trump_Teaser.setText(_translate("StackedWidget", "The President of the United States declared war via Twitter. Is this reliable?"))
        self.N_HSV_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_GoT_Head.setText(_translate("StackedWidget", "Game of Thrones: Big Cast Changes in Season 8"))
        self.N_Munich_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_Merkel_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_Trump_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_Bottom.setText(_translate("StackedWidget", "© NEWS TODAY INC. BERLIN"))
        self.N_Acc_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_GoT_Teaser.setText(_translate("StackedWidget", "HBO announced, that these actors will not return for the last season. Who and why?"))
        self.N_Merkel_Teaser.setText(_translate("StackedWidget", "What did really happen between Merkel and Obama? Was this only a platonic relationship? \n"
"You will never believe the true story!"))
        self.N_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.N_GoT_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_JD_Head.setText(_translate("StackedWidget", "How Johnny Depp wants to change Hollywood"))
        self.N_JD_Button.setText(_translate("StackedWidget", "Read more..."))
        self.N_Munich_Teaser.setText(_translate("StackedWidget", "The prices for flats and houses in Munich are still growing. Locals are scared.  \n"
"Could this cause an increase of homeless people?"))
        self.N_HSV_Teaser.setText(_translate("StackedWidget", "The Madrid Superstar just signed the Contract and starts in the next \n"
"season in Hamburg."))
        self.N_Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.N_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.N_HSV_Head.setText(_translate("StackedWidget", "HSV signs Madrid Superstar"))
        self.N_Acc_Teaser.setText(_translate("StackedWidget", "Yesterday the whole Autobahn around Berlin had to be blocked by the police. \n"
"What did really happen?"))
        self.GoT_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.GoT_JD_Head.setText(_translate("StackedWidget", "Johnny Depp about \n"
"his new ideas for Hollywood"))
        self.GoT_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.GoT_JD_Button.setText(_translate("StackedWidget", "Read more..."))
        self.GoT_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.GoT_Teaser.setText(_translate("StackedWidget", "HBO announced, that these actors will not return for the last season. Who and why?"))
        self.GoT_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.GoT_HSV_Head.setText(_translate("StackedWidget", "HSV signs Madrid superstar"))
        self.GoT_Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising. \n"
"Inreasing number of \n"
"homeless people in the city?"))
        self.GoT_Munich_Button.setText(_translate("StackedWidget", "Read more..."))
        self.GoT_HSV_Button.setText(_translate("StackedWidget", "Read more..."))
        self.GoT_Head.setText(_translate("StackedWidget", "Game of Thrones: Big Cast Changes in Season 8"))
        self.GoT_Text.setText(_translate("StackedWidget", "The Cast of Game of Thrones is going to change in the next and final season. A few of the actors \n"
"are leaving the series, including Joe Dempsey and Daniel Portman. Also some of the minor roles \n"
"and actors who took part in the fighting and war scenes are leaving the set."))
        self.HSV_Head.setText(_translate("StackedWidget", "HSV signs Madrid Superstar"))
        self.HSV_JD_Button.setText(_translate("StackedWidget", "Read more..."))
        self.HSV_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.HSV_Trump_Button.setText(_translate("StackedWidget", "Read more..."))
        self.HSV_JD_Head.setText(_translate("StackedWidget", "Johnny Depp about \n"
"his new ideas for Hollywood"))
        self.HSV_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.HSV_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.HSV_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.HSV_Teaser.setText(_translate("StackedWidget", "The Madrid Superstar just signed the Contract and starts in the next \n"
"season in Hamburg."))
        self.HSV_GoT_Head.setText(_translate("StackedWidget", "GAME OF THRONES \n"
"Changes announced"))
        self.HSV_GoT_Button.setText(_translate("StackedWidget", "Read more..."))
        self.HSV_Text.setText(_translate("StackedWidget", "HAMBURG. The football club just signed newcomer Juan from the third team of Madrid. \n"
"He is going to start in September for the next season."))
        self.HSV_Trump_Head.setText(_translate("StackedWidget", "Trump declares war via Twitter"))
        self.Acc_HSV_Head.setText(_translate("StackedWidget", "HSV signs Madrid superstar"))
        self.Acc_Merkel_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Acc_HSV_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Acc_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.Acc_Head.setText(_translate("StackedWidget", "Car accident causes trouble near Berlin"))
        self.Acc_Trump_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Acc_Text.setText(_translate("StackedWidget", "BERLIN. After a huge car accident involving two cars and one truck the Autobahn \n"
"had to be blocked. 3 people were injured. The police is investigating the progression of events."))
        self.Acc_Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.Acc_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.Acc_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.Acc_Trump_Head.setText(_translate("StackedWidget", "Trump declares war via Twitter"))
        self.Acc_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.Acc_Teaser.setText(_translate("StackedWidget", "Yesterday the whole Autobahn around Berlin had to be blocked by the police. \n"
"What did really happen?"))
        self.Trump_Head.setText(_translate("StackedWidget", "Trump declares war via Twitter"))
        self.Trump_Teaser.setText(_translate("StackedWidget", "The President of the United States declared war via Twitter. Is this reliable?"))
        self.Trump_HSV_Head.setText(_translate("StackedWidget", "HSV signs Madrid superstar"))
        self.Trump_Munich_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Trump_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.Trump_Text.setText(_translate("StackedWidget", "WASHINGTON. US President Donald Trump tweetet, that if North Korea \n"
"is not willing to change their behaviour he is going to start the war. Trump is well known for connecting to \n"
"the people (including head of states) through the Social Medium."))
        self.Trump_HSV_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Trump_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.Trump_Merkel_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Trump_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.Trump_Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.Trump_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.Trump_Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising. \n"
"Inreasing number of \n"
"homeless people in the city?"))
        self.JD_GoT_Button.setText(_translate("StackedWidget", "Read more..."))
        self.JD_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.JD_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.JD_Teaser.setText(_translate("StackedWidget", "He has an idea, which might change the story of Hollywood. Is he a genius or a maniac?"))
        self.JD_Head.setText(_translate("StackedWidget", "How Johnny Depp wants to change Hollywood"))
        self.JD_Teaser_2.setText(_translate("StackedWidget", "LOS ANGELES. Johnny Depp tweetet about his new movie idea in cooperation with Tim Burton. \n"
"This is a mix of Pirates of the Caribbean and Nightmare before Christmas \n"
"We are excited to see how this idea is going to develop."))
        self.JD_Merkel_Button.setText(_translate("StackedWidget", "Read more..."))
        self.JD_Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.JD_Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising. \n"
"Inreasing number of \n"
"homeless people in the city?"))
        self.JD_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.JD_GoT_Head.setText(_translate("StackedWidget", "GAME OF THRONES \n"
"Changes announced"))
        self.JD_Munich_Button.setText(_translate("StackedWidget", "Read more..."))
        self.JD_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.Munich_GoT_Head.setText(_translate("StackedWidget", "GAME OF THRONES \n"
"Changes announced"))
        self.Munich_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.Munich_Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.Munich_Trump_Head.setText(_translate("StackedWidget", "Trump declares war via Twitter"))
        self.Munich_GoT_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Munich_Merkel_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Munich_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.Munich_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising"))
        self.Munich_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.Munich_Teaser.setText(_translate("StackedWidget", "The prices for flats and houses in Munich are still growing. Locals are scared.  \n"
"Could this cause an increase of homeless people?"))
        self.Munich_Text.setText(_translate("StackedWidget", "MUNICH. The rents in Munich are still rising. Due to this, the number of homeless people could rise in the \n"
"next years.   Mabye... There is no scientific study, that shows something like that, but it sounds plausible."))
        self.Munich_Trump_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Merkel_Head.setText(_translate("StackedWidget", "More than \"Friendship\"?"))
        self.Merkel_Teaser.setText(_translate("StackedWidget", "What did really happen between Merkel and Obama? Was this only a platonic relationship? \n"
"You will never believe the true story!"))
        self.Merkel_Ad.setText(_translate("StackedWidget", "Read now:"))
        self.Merkel_Text.setText(_translate("StackedWidget", "BERLIN. Merkel and Obama always claimed they were friends, but maybe they are not...\n"
"Actually they are. But... Who knows? Let\'s make up a story!"))
        self.Merkel_Munich_Head.setText(_translate("StackedWidget", "Rents in Munich keep rising. \n"
"Inreasing number of \n"
"homeless people in the city?"))
        self.Merkel_Munich_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Merkel_Top_Head.setText(_translate("StackedWidget", "News \n"
"      Today"))
        self.Merkel_JD_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Merkel_Home_Button.setText(_translate("StackedWidget", "<< home"))
        self.Merkel_Top_Date.setText(_translate("StackedWidget", "Mon, August 14 2017"))
        self.Merkel_GoT_Button.setText(_translate("StackedWidget", "Read more..."))
        self.Merkel_JD_Head.setText(_translate("StackedWidget", "Johnny Depp about \n"
"his new ideas for Hollywood"))
        self.Merkel_GoT_Head.setText(_translate("StackedWidget", "GAME OF THRONES \n"
"Changes announced"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StackedWidget = QtWidgets.QStackedWidget()
    ui = Ui_StackedWidget()
    ui.setupUi(StackedWidget)
    StackedWidget.show()
    sys.exit(app.exec_())
